name: multistreamer
description: Stream video URLs directly using YouTube-DL

publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^5.0.2
  app_links: ^6.1.4
  html: ^0.15.1
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png

